apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: console-app-job
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: console-app-container
            image: johanneseh/console-app
          restartPolicy: OnFailure